language: node_js
sudo: false
node_js:
  - stable
  - lts/dubnium

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache
install: npm install --build-from-source
after_success: cat ./coverage/lcov.info | coveralls
